app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class PokeForm(FlaskForm):
	name = StringField('Pokemon Name', validators=[DataRequired()])
	submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Login required'
login.login_message_category = 'warning'

db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
	app = Flask(__name__)
	app.config.from_object(config_class)

	login.init_app(app)
	db.init_app(app)
	migrate.init_app(app, db)

	from .blueprints.main import bp as main_bp
	app.register_blueprint(main_bp)

	from .blueprints.auth import bp as auth_bp
	app.register_blueprint(auth_bp)

	return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='')

from . import routes

app/blueprints/main/routes.py
from flask import render_template, request, g
from flask_login import login_required
import requests

from . import bp as main
from .forms import PokeForm

@main.route('/')
@login_required
def index():
	return render_template('index.html')

#Makes a string Look Like This instead-of-like-this
def fmt(string):
	return string.title().replace('-', ' ')

#Yoinks the desired info out of the json from the api
def get_info(data):
	stats = []
	#Grab all the stats and stick them in a list
	for stat in data['stats']:
		stinfo = {}
		stinfo['name'] = fmt(stat['stat']['name'])
		stinfo['level'] = stat['base_stat']
		stats.append(stinfo)
	#Grab the rest of the info and throw everything into a dictionary
	return {
		'abilities': [fmt(ability['ability']['name']) for ability in data['abilities']],
		'exp': data['base_experience'],
		'name': fmt(data['name']),
		'sprite': data['sprites']['front_shiny'],
		'types': [fmt(tp['type']['name']) for tp in data['types']],
		'stats': stats
	}

@main.route('/pokemon', methods=['GET', 'POST'])
@login_required
def pokemon():
	form = PokeForm()
	#Check if the user has loaded this page by pressing the submit button
	if request.method == 'POST' and form.validate_on_submit():
		#Load the response for the pokemon name given
		name = request.form.get('name')
		response = requests.get(f"https://pokeapi.co/api/v2/pokemon/{name.lower().replace(' ', '-')}")
		#Break if broken
		if not response.ok:
			return render_template('pokemon.html', error='Error: Bad request', form=form)
		#Break if broken (again)
		try:
			info = get_info(response.json())
			return render_template('pokemon.html', info=info, form=form)
		except:
			return render_template('pokemon.html', error="Error: Error processing response", form=form)
	return render_template('pokemon.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="Description" content="Enter your description here" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

	<link rel="shortcut icon" href="{{url_for('static', filename='images/apple-touch-icon.png')}}">
	<link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/apple-touch-icon.png')}}">
	<link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='images/favicon-32x32.png')}}">
	<link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='images/favicon-16x16.png')}}">

	<title>
		{% block title %}
		{% endblock %}
	</title>

	{% include './includes/nav.html' %}
	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for class, message in messages %}
			<div class="alert alert-{{class}} alert-dismissable fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
			</div>
			{% endfor %}
		{% endif %}
	{% endwith %}

</head>

<body>

	<div class="container">
		{% block content %}
		{% endblock %}
	</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
			aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				{% if current_user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{url_for('main.index')}}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{url_for('main.pokemon')}}">Pokemon</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{url_for('auth.edit_profile')}}">Edit Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{url_for('auth.logout')}}">Logout</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{url_for('auth.register')}}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{{url_for('auth.login')}}">Login</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Welcome, user! Go to the Pokemon tab to start looking up Pokemon!</h1>
{% endblock %}

app/templates/pokemon.html
{% extends 'base.html' %}

{% block title %}
Pokemon Lookup
{% endblock %}

{% block content %}
<!--<form action="/pokemon" method="POST">
	<div class="form-group">
		<label for="name">Pokemon Name</label>
		<input type="text" name="name" class="form-control" id="name">
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>
</form>-->

<form action="{{url_for('main.pokemon')}}" method="POST">
	{{ form.hidden_tag() }}
	{{ form.name.label(class="form-label") }}
	{{ form.name(class="form-control") }}
	{{ form.submit(class="btn btn-primary") }}
</form>

{% if info %}
<div class="info">
	<div class="wrapper">
		<ul class="list-group">
			<li class="list-group-item active">{{info['name']}}</li>
			<li class="list-group-item">Type(s): {{', '.join(info['types'])}}</li>
			<li class="list-group-item">Abilities: {{', '.join(info['abilities'])}}</li>
			<li class="list-group-item">Base Experience: {{info['exp']}}</li>
			{% for stat in info['stats'] %}
			<li class="list-group-item">Base {{stat['name']}}: {{stat['level']}}</li>
			{% endfor %}
		</ul>
	</div>
	<div class="wrapper">
		<img src="{{info['sprite']}}">
	</div>
</div>
{% endif %}
<small style="color: red">{{error}}</small>
{% endblock %}